# Analisis de Datos Con IA
## Proyecto 03

In [63]:
!pip install yfinance

Requirement already satisfied: yfinance in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.7.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (4.15.0)
Requirement already satisfied: curl_cffi>=0.15 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (0.16.3)
Requirement already satisfied: lxml>=4.9.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (6.1.3)
Requirement already satisfied: multitasking>=0.0.7 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: numpy>=1.16.5 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (2.5.3)
Requirement already satisfied: pandas>=1.3.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (3.0.5)
Requirement already satisfied: peewee>=3.16.2 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (4.5.1)
Requirement already satisfied: platformdirs>=2.0.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python314\site-packages (from yfinance) (4.11.8)
Requirement already satisfied: protobuf>=3.19.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (7.36.1)
Requirement already satisfied: pytz>=2022.5 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (2026.3.post1)
Requirement already satisfied: requests>=2.31 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (2.34.2)
Requirement already satisfied: websockets>=13.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (16.1.1)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python314\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.7.22)
Requirement already satisfied: pycparser in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.3.0->yfinance) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.31->yfinance) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.31->yfinance) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.31->yfinance) (2.8.0)

In [64]:
!pip install plotly 
!pip install google-genai
!pip install nbformat
!pip install pandas

Requirement already satisfied: plotly in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (7.1.0)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from plotly) (2.26.0)
Requirement already satisfied: packaging in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from plotly) (26.3)
Requirement already satisfied: google-genai in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.24.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from google-genai) (4.15.1)
Requirement already satisfied: google-auth<3.0.0,>=2.56.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.58.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.12.5 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from google-genai) (2.13.5)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from google-genai) (2.34.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from google-genai) (16.1.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python314\site-packages (from google-genai) (4.16.0)
Requirement already satisfied: distro<2,>=1.7.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.19)
Requirement already satisfied: pyasn1-modules>=0.2.1 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=41.0.5 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (50.0.1)
Requirement already satisfied: certifi in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.7.22)
Requirement already satisfied: httpcore==1.* in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.8.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cryptography>=41.0.5->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.1.1)
Requirement already satisfied: pycparser in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cffi>=2.0.0->cryptography>=41.0.5->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.6.4)
Requirement already satisfied: nbformat in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (5.11.1)
Requirement already satisfied: fastjsonschema>=2.15 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from nbformat) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\LENOVO\AppData\Roaming\Python\Python314\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in C:\Users\LENOVO\AppData\Roaming\Python\Python314\site-packages (from nbformat) (5.16.1)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=2.6->nbformat) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\LENOVO\AppData\Roaming\Python\Python314\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.11.8)
Requirement already satisfied: pandas in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\LENOVO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [65]:
import yfinance as yf

In [66]:
tikers = ["AAPL", "NVDA", "MSFT"]
datos = yf.download(tikers, period="1y")

precios = datos['Close']

[*********************100%***********************]  3 of 3 completed

In [67]:
precios.head()

Ticker            AAPL        MSFT        NVDA
Date
2025-09-17  238.110443  505.857941  169.882980
2025-09-18  237.004517  504.300812  175.818787
2025-09-19  244.596451  513.703430  176.247726
2025-09-22  255.137512  510.251892  183.171158
2025-09-23  253.493607  505.074432  178.003540

In [68]:
precios.tail()

Ticker            AAPL        MSFT        NVDA
Date
2026-09-10  326.570007  492.440002  218.360001
2026-09-11  332.269989  495.630005  218.289993
2026-09-14  333.079987  505.410004  210.960007
2026-09-15  331.339996  497.119995  212.169998
2026-09-16  332.410004  490.299988  213.899994

# Estadisticas

In [69]:
precios.describe()

Ticker        AAPL        MSFT        NVDA
count   251.000000  251.000000  251.000000
mean    280.320195  445.594004  195.247086
std      25.421896   51.010052   15.696685
min     237.004517  352.167023  164.793320
25%     259.480286  398.700577  182.722298
50%     272.657806  449.394012  190.085205
75%     302.704285  492.162018  208.102142
max     339.786926  537.646362  235.202393

# Graficos interactivos

In [70]:
import plotly.express as px

In [71]:
grafica = px.line(precios, x=precios.index, y=precios.columns, title="Precios de Cierre de AAPL, NVDA y MSFT en el ultimo año",
                  template = "plotly_dark", labels = {"value": "Precio (USD)", "variable": "Acción"})

In [72]:
grafica

In [73]:
px.line(precios["AAPL"],
        title = "Cotizacion historica de AAPL(ultimos doce meses)",
        labels = {"Value": "Precio (USD)", "Date": "Fecha"},
        template = "plotly_dark")

In [74]:
px.bar(precios.mean(axis=0),
       title = "Promedio de precios de cierre de AAPL, NVDA Y MSFT en el ultimo año",
       labels = {"value": "Precio (USD)", "index": "Accion"},
       color = precios.mean(axis=0),
       template = "plotly_dark",)

## Acceder a las filas de nuestros datos

In [75]:
precios

Ticker            AAPL        MSFT        NVDA
Date
2025-09-17  238.110443  505.857941  169.882980
2025-09-18  237.004517  504.300812  175.818787
2025-09-19  244.596451  513.703430  176.247726
2025-09-22  255.137512  510.251892  183.171158
2025-09-23  253.493607  505.074432  178.003540
...                ...         ...         ...
2026-09-10  326.570007  492.440002  218.360001
2026-09-11  332.269989  495.630005  218.289993
2026-09-14  333.079987  505.410004  210.960007
2026-09-15  331.339996  497.119995  212.169998
2026-09-16  332.410004  490.299988  213.899994

[251 rows x 3 columns]

In [76]:
precios.values[2]

array([244.59645081, 513.70343018, 176.24772644])

In [77]:
inversion = precios / precios.values[2] * 1000

In [78]:
fig =px.line(inversion, x=inversion.index, y=inversion.columns, title="Inversion de 1000 USD en AAPL, NVDA y MSFT hace un año",
        labels = {"value": "Valor de la inversion (USD)", "variable": "Accion"},
        template = "plotly_dark")

In [79]:
fig.write_html("inversion.html")

# Informe con IA

In [62]:
from google import genai as gemini 

cliente = gemini.Client(api_key="AQ.Ab8RN6Jo4zkETKqQ1WzWFbYKyejkHLmtnGvicLZqb0rvbiFOFQ")

prompt = f""" Haz un analisis de la cotizacion de AAPL, NVDA y MSFT en el ultimo año y genera un resumen de 5 lineas.
{precios}
"""

respuesta = cliente.models.generate_content(
    model = "gemini-3.5-flash",
    contents = prompt
)

In [80]:
print(respuesta.text)

Aquí tienes el análisis del comportamiento de las acciones de **AAPL**, **NVDA** y **MSFT** durante el periodo del 17 de septiembre de 2025 al 15 de septiembre de 2026 (251 días bursátiles):

* **AAPL (Apple):** Presentó el mejor rendimiento del grupo, subiendo de **$238.11** a **$331.34**, lo que representa un espectacular crecimiento del **+39.15%**, consolidando una fuerte tendencia alcista.
* **NVDA (NVIDIA):** Continuó con un sólido desempeño positivo, pasando de **$169.88** a **$212.17**, logrando un incremento del **+24.89%** a pesar de la volatilidad implícita del sector de semiconductores.
* **MSFT (Microsoft):** Mostró un comportamiento plano y de consolidación, iniciando en **$505.86** y cerrando en **$497.12**, lo que equivale a una leve corrección del **-1.73%**, manteniéndose estable alrededor de la barrera psicológica de los $500.

***

### Resumen de 5 líneas:

1. AAPL lideró el crecimiento anual con un impresionante rendimiento del +39.15%, cerrando con fuerza en $331.34 USD.
2. NVDA consolidó su tendencia alcista al registrar un avance del +24.89%, finalizando el periodo en $212.17 USD.
3. MSFT mostró un comportamiento plano y defensivo, con una leve contracción del -1.73% alrededor de los $500 USD.
4. El sector tecnológico evidenció un avance asimétrico, donde el hardware y consumo (Apple/Nvidia) superaron al software (Microsoft).
5. En balance general, el conjunto de las tres empresas generó un saldo netamente positivo y de alto rendimiento anual.

In [81]:
Informe = respuesta.text

In [83]:
Informe

'Aquí tienes el análisis del comportamiento de las acciones de **AAPL**, **NVDA** y **MSFT** durante el periodo del 17 de septiembre de 2025 al 15 de septiembre de 2026 (251 días bursátiles):\n\n* **AAPL (Apple):** Presentó el mejor rendimiento del grupo, subiendo de **$238.11** a **$331.34**, lo que representa un espectacular crecimiento del **+39.15%**, consolidando una fuerte tendencia alcista.\n* **NVDA (NVIDIA):** Continuó con un sólido desempeño positivo, pasando de **$169.88** a **$212.17**, logrando un incremento del **+24.89%** a pesar de la volatilidad implícita del sector de semiconductores.\n* **MSFT (Microsoft):** Mostró un comportamiento plano y de consolidación, iniciando en **$505.86** y cerrando en **$497.12**, lo que equivale a una leve corrección del **-1.73%**, manteniéndose estable alrededor de la barrera psicológica de los $500.\n\n***\n\n### Resumen de 5 líneas:\n\n1. AAPL lideró el crecimiento anual con un impresionante rendimiento del +39.15%, cerrando con fuerza en $331.34 USD.\n2. NVDA consolidó su tendencia alcista al registrar un avance del +24.89%, finalizando el periodo en $212.17 USD.\n3. MSFT mostró un comportamiento plano y defensivo, con una leve contracción del -1.73% alrededor de los $500 USD.\n4. El sector tecnológico evidenció un avance asimétrico, donde el hardware y consumo (Apple/Nvidia) superaron al software (Microsoft).\n5. En balance general, el conjunto de las tres empresas generó un saldo netamente positivo y de alto rendimiento anual.'